### ISSUE TITLE
Support for web

### ISSUE THREAD

**Issue by AlejandraPedroza** [xxfast/NYTimes-KMP#101]
Hello,

I'm a Kotlin technical writer at JetBrains, currently working on updating the [Kotlin Multiplatform samples page](https://www.jetbrains.com/help/kotlin-multiplatform-dev/multiplatform-samples.html). This project is listed there, and as part of the update, I am mapping the samples to the platforms they support. As support for web is announced in this project, we tested it, but we couldn't make it work. For this reason, we couldn't promote NYTimes KMP as web in our samples page.

Given our goal of providing users with the best multiplatform experience, I wonder if there's an opportunity to update this project to include not only proper support, but also clearer instructions so that users can successfully run the app on the web platform. 

Thank you in advance for considering this!

Best regards,

Alejandra Pedroza.

**Comment by xxfast** [comment]
Hi @AlejandraPedroza 

Currently, NYTimes works only on js target (as seen here https://xxfast.github.io/NYTimes-KMP/) but I'm working on adding the support for the wasm target (for which I had to add wasm support for my other two libraries [KStore](https://github.com/xxfast/KStore) and [Decompose Router](https://github.com/xxfast/Decompose-Router) - which is now unblocked)

Do you know what issues did you run into running the js client? 

Cheers

**Comment by xxfast** [comment]
Hi @AlejandraPedroza 

I just added support for wasm targets and updated the readme with run instructions. Let me know if this is suffice

**Comment by AlejandraPedroza** [comment]
Hi! This is great! Thanks for the update. I'll test support for Kotlin//wasm and update our sample pages to mention that NYTimes KMP has support for the web. 

Regarding the Js target, this is the issue we found when testing it:

The "browser" run configuration did not work:

```
ClassCastException
    at THROW_CCE (webpack-internal:///./kotlin/kotlin-kotlin-stdlib.js:5316:11)
    at CanvasBasedWindow (webpack-internal:///./kotlin/compose-multiplatform-core-compose-ui-ui.js:50163:63)
    at main$lambda (webpack-internal:///./kotlin/NYTimes-KMP-client-web.js:102:5)
```

Best regards,
Alejandra.
