### ISSUE TITLE
Unable to run ios app

### ISSUE THREAD

**Issue by TheReprator** [xxfast/NYTimes-KMP#36]
First thank you for this wonderful project.

Right now, i am unable to run the ios project, getting error("/Users/code/kmp/NYTimes-KMP/app/ios/Pods/Target Support Files/Pods-ios/Pods-ios.debug.xcconfig:1:1 unable to open configuration settings file
")

Attaching image for reference.

<img width="1422" alt="Screenshot 2023-05-31 at 9 44 50 PM" src="https://github.com/xxfast/NYTimes-KMP/assets/10286587/6478d51f-ed59-44a8-8f25-278909a7ff6d">

**Comment by xxfast** [comment]
Hi. Thanks for the issue. 

Did you open the xcode project file or xcode workspace? Can you check if you run into the same issue if you open the workspace?

**Comment by TheReprator** [comment]
I ran the .workspace file

**Comment by xxfast** [comment]
Can you check if you can build with the release scheme?

**Comment by TheReprator** [comment]
I think, it doesn't exist in folder, even after rebuilding/reconfiguring/reinstalling the pod
<img width="1414" alt="Screenshot 2023-06-09 at 11 30 12 AM" src="https://github.com/xxfast/NYTimes-KMP/assets/10286587/e9b33022-33dc-419e-be4f-173c7324fbbc">

**Comment by ghost** [comment]
What was the solution to this? I am facing the same error
