### ISSUE TITLE
Web phone doesn't work

### ISSUE THREAD

**Issue by GazimSoliev** [xxfast/NYTimes-KMP#63]
I tried to launch web in phone and it doesn't work, I cannot scroll my interface

**Comment by xxfast** [comment]
Hi @GazimSoliev Thanks for the issue. Unfortunately, this is not yet supported on Compose-multiplatform https://github.com/JetBrains/compose-multiplatform/issues/3491

I will reopen this issue once compose-multiplatform adds support for this
